name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: MAINKS
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push the content of <build_dir> to a branch
      - name: push github-contribution-grid-snake.svg to the output branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git clone --single-branch --branch output https://github.com/MAINKS/MAINKS.git output
          cp -r dist/* output/
          cd output
          git add .
          git commit -m "Update github-contribution-grid-snake.svg"
          git push https://PAT_TOKEN@github.com/MAINKS/MAINKS.git output
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
